CREATE DATABASE dadosfinanceiros;
USE dadosfinanceiros;

CREATE TABLE operadoras_saude (
    REGISTRO_ANS VARCHAR(6) PRIMARY KEY,
    CNPJ VARCHAR(14),
    RAZAO_SOCIAL VARCHAR(255),
    NOME_FANTASIA VARCHAR(100),
    MODALIDADE VARCHAR(100),
    LOGRADOURO VARCHAR(255),
    NUMERO VARCHAR(10),
    COMPLEMENTO VARCHAR(100),
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100),
    UF VARCHAR(2),
    CEP VARCHAR(10),
    DDD VARCHAR(2),
    TELEFONE VARCHAR(10),
    FAX VARCHAR(10),
    ENDERECO_ELETRONICO VARCHAR(100),
    REPRESENTANTE VARCHAR(100),
    CARGO_REPRESENTANTE VARCHAR(100),
    REGIAO_DE_COMERCIALIZACAO INT,
    DATA_REGISTRO_ANS DATE
);

CREATE TABLE demonstracoes_contabeis (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA DATE,
    REG_ANS VARCHAR(6),
    CD_CONTA_CONTABIL VARCHAR(20),
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL(15, 2),
    VL_SALDO_FINAL DECIMAL(15, 2),
    FOREIGN KEY (REG_ANS) REFERENCES operadoras_saude(REGISTRO_ANS) ON DELETE CASCADE ON UPDATE CASCADE
)

